packages:
  - "."

allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: true
  prisma: set this to true or false

minimumReleaseAgeExclude:
  - '@tanstack/form-core@1.33.3'
  - '@tanstack/react-form@1.33.3'
