packages:
  - "."
# dependency behavior
dedupeDirectDeps: true

# hoisting behavior
hoist: true
shamefullyHoist: true

ignoreWorkspaceRootCheck: true

allowBuilds:
  esbuild: true

minimumReleaseAge: 0