name: Eleventy Build

on:
  push:
    branches:
      - master
  schedule:
    # everyday at 8 PM UTC
    - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --shamefully-hoist
      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: public
          CNAME: rubiin.is-a.dev
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
