import { cn } from '@/lib/utils'

/**
 * Responsive <picture>: serves AVIF first, falls back to WebP, and picks
 * the best width from the viewport via `sizes`/`srcset`. Variant files are
 * generated by `scripts/optimize-images.mjs` following the naming
 * `${base}-${w}.{avif,webp}`; the full-size source is the unsuffixed
 * `${base}.{avif,webp}` (the last entry in `widths`).
 */
// Note: the last `widths` entry is the common native width for that image
// kind (e.g. 800 for project shots). A few projects are slightly narrower
// (500–700w), so that full-size `w` descriptor can overstate the file —
// harmless in the current card grids (~370px cells always pick a smaller
// candidate) and avoided machinery to track per-image widths.
export function ResponsiveImage({
  src,
  alt,
  widths,
  sizes,
  width,
  height,
  loading = 'lazy',
  className,
}: {
  /** Full-size WebP path, e.g. '/projects/finkey.webp' (also the fallback). */
  src: string
  alt: string
  /** Width candidates in px — the last entry is the full-size (unsuffixed) file. */
  widths: number[]
  /** `sizes` attribute — the rendered width of the image in the layout. */
  sizes: string
  width?: number
  height?: number
  loading?: 'lazy' | 'eager'
  className?: string
}) {
  const base = src.replace(/\.webp$/, '')
  const full = widths[widths.length - 1]
  const candidates = (ext: string) => [
    ...widths.slice(0, -1).map((w) => `${base}-${w}.${ext} ${w}w`),
    `${base}.${ext} ${full}w`,
  ]

  if (!src.endsWith('.webp')) {
    return (
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        decoding="async"
        className={cn('size-full object-cover', className)}
      />
    )
  }

  return (
    <picture>
      <source type="image/avif" srcSet={candidates('avif').join(', ')} sizes={sizes} />
      <source type="image/webp" srcSet={candidates('webp').join(', ')} sizes={sizes} />
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        decoding="async"
        className={cn('size-full object-cover', className)}
      />
    </picture>
  )
}
